"""Letter of Protest PDF — standard maritime format.

Required: reportlab.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Optional

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ._pdfutil import paragraph_text, xml_escape
from .config import FUEL_PRICE, PDF_MARGIN, session_dir

if TYPE_CHECKING:
    from ._extract import ViewBundle


def generate_lop(
    view: "ViewBundle",
    *,
    output_dir: Optional[Path] = None,
) -> Path:
    """Render a formal LoP PDF.

    Uses the LLM-drafted ``lop_draft`` if available; otherwise generates a
    standard template grounded in the BDN + MFM numbers.
    """
    out_dir = output_dir or session_dir(view.session_id)
    filepath = out_dir / f"LetterOfProtest_{view.session_id}.pdf"

    doc = SimpleDocTemplate(
        str(filepath), pagesize=A4,
        leftMargin=PDF_MARGIN, rightMargin=PDF_MARGIN,
        topMargin=PDF_MARGIN, bottomMargin=PDF_MARGIN,
    )
    styles = _build_styles()

    bdn, mfm = view.bdn, view.mfm
    qty_diff = abs(mfm["cumulative_mass"] - bdn["quantity_mt"])
    qty_pct = (qty_diff / bdn["quantity_mt"]) * 100 if bdn["quantity_mt"] else 0.0
    unit_price = FUEL_PRICE.get(bdn["grade"], 585.0)
    impact_usd = view.risk.get("financial_impact") or (qty_diff * unit_price)

    elements: list = []
    elements.append(Paragraph("LETTER OF PROTEST", styles["LOP_Title"]))
    elements.append(Paragraph(
        f"Date: {datetime.now().strftime('%d %B %Y')}", styles["LOP_Body"]))
    elements.append(Paragraph(
        f"Reference: LoP-{view.session_id}", styles["LOP_Body"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(
        "To: The Master / Supplier Representative", styles["LOP_Bold"]))
    elements.append(Paragraph(
        f"Supplier: {xml_escape(bdn['supplier_name'])}", styles["LOP_Body"]))
    elements.append(Paragraph(
        f"Barge: {xml_escape(bdn['barge_name'])}", styles["LOP_Body"]))
    elements.append(Spacer(1, 8))

    elements.append(Paragraph(
        f"From: Chief Engineer, {xml_escape(bdn['vessel_name'])} "
        f"(IMO {xml_escape(bdn['vessel_imo'])})",
        styles["LOP_Bold"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph(
        f"Re: Bunkering Operation at {xml_escape(bdn['port'])} "
        f"on {xml_escape(bdn['date'])}",
        styles["LOP_Bold"]))
    elements.append(Spacer(1, 8))

    llm_draft = (view.llm_analysis or {}).get("lop_draft")
    if llm_draft:
        # paragraph_text keeps \n\n -> <br/><br/>, so the LLM's paragraphs survive.
        elements.append(Paragraph(paragraph_text(llm_draft), styles["LOP_Body"]))
    else:
        elements.extend(_template_body(view, styles, qty_diff, qty_pct, impact_usd))

    elements.append(Spacer(1, 30))
    elements.append(_signature_block())
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "This Letter of Protest was auto-generated by BunkerGuard AI and "
        "should be reviewed before signing.",
        styles["LOP_Small"],
    ))

    doc.build(elements)
    return filepath


def _build_styles() -> dict:
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        "LOP_Title", fontSize=16, fontName="Helvetica-Bold",
        alignment=TA_CENTER, spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        "LOP_Body", fontSize=10, fontName="Helvetica",
        leading=14, alignment=TA_JUSTIFY, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "LOP_Bold", fontSize=10, fontName="Helvetica-Bold",
        leading=14, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "LOP_Small", fontSize=8, fontName="Helvetica",
        textColor=HexColor("#666666"),
    ))
    return styles


def _template_body(view, styles, qty_diff, qty_pct, impact_usd) -> list:
    bdn, mfm = view.bdn, view.mfm
    items: list = [
        Paragraph(
            f"We hereby formally protest against the following discrepancies "
            f"noted during the bunkering operation conducted on "
            f"{xml_escape(bdn['date'])} at {xml_escape(bdn['port'])}:",
            styles["LOP_Body"],
        ),
        Spacer(1, 6),
    ]
    for a in view.anomalies:
        items.append(Paragraph(
            f"* [{xml_escape(a['severity'])}] "
            f"{xml_escape(a.get('name', ''))} - "
            f"{xml_escape(a.get('description', ''))}",
            styles["LOP_Body"],
        ))

    items.append(Spacer(1, 8))
    items.append(Paragraph(
        f"The Bunker Delivery Note (Ref: {xml_escape(bdn['bdn_ref'])}) "
        f"declares a delivered quantity of {bdn['quantity_mt']:.1f} MT of "
        f"{xml_escape(bdn['product_grade'])}. However, our Mass Flow Meter "
        f"(MPA-approved, calibrated per SS 648) recorded a total of "
        f"{mfm['cumulative_mass']:.1f} MT, representing a shortfall of "
        f"{qty_diff:.1f} MT ({qty_pct:.2f}%).",
        styles["LOP_Body"],
    ))
    items.append(Paragraph(
        f"The estimated financial impact of this discrepancy is "
        f"USD ${impact_usd:,.2f}.",
        styles["LOP_Body"],
    ))
    items.append(Spacer(1, 8))
    items.append(Paragraph(
        "We reserve all our rights to claim for the above discrepancies and "
        "any consequential losses. We request that you acknowledge this "
        "protest and take immediate corrective action.",
        styles["LOP_Body"],
    ))
    return items


def _signature_block() -> Table:
    rows = [[
        "Chief Engineer\n\n\n\n___________________\nName:\nDate:",
        "Supplier Representative\n\n\n\n___________________\nName:\nDate:",
        "Witness (Surveyor)\n\n\n\n___________________\nName:\nDate:",
    ]]
    st = Table(rows, colWidths=[160, 160, 160])
    st.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return st


# XML escape moved to outputs._pdfutil — see top of file.
