import { createClient } from '@supabase/supabase-js';

/**
 * Single Supabase client used across the FE.
 *
 * Configure via Vite env vars in `.env.local` (gitignored):
 *
 *   VITE_SUPABASE_URL=https://jdnzznxwdczcktfqwxmj.supabase.co
 *   VITE_SUPABASE_ANON_KEY=<your anon key>
 *
 * For dev convenience we accept the **service_role** JWT in
 * `VITE_SUPABASE_ANON_KEY` slot — it bypasses RLS so the panels work without
 * policies being defined yet. Before shipping to production, swap to the
 * project's anon key + add row-level-security policies on each table.
 */

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? 'https://jdnzznxwdczcktfqwxmj.supabase.co';
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? '';

if (!SUPABASE_KEY) {
  // Surface a clear console warning rather than failing every query silently.
  // eslint-disable-next-line no-console
  console.warn(
    '[supabase] VITE_SUPABASE_ANON_KEY is empty. Set it in .env.local — without it every PostgREST request returns 401.',
  );
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  auth: { persistSession: false },
});

/* ─── Domain types — generated by hand from the OpenAPI doc ───────────── */

export type RiskCategory = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type SessionStatus = 'BUNKERING' | 'COMPLETED' | 'DISPUTED' | 'PENDING' | string;
export type AnomalySeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type SupplierFlag = 'GOOD' | 'MONITORING' | 'FLAGGED' | 'SUSPENDED' | string;

export interface SessionRow {
  session_id: string;
  vessel_name: string;
  vessel_imo: string;
  barge_name: string | null;
  barge_imo: string | null;
  supplier_id: string | null;
  supplier_name: string | null;
  port: string | null;
  fuel_grade: string | null;
  bdn_qty_mt: number | null;
  mfm_qty_mt: number | null;
  dev_mt: number | null;
  dev_pct: number | null;
  risk_score: number | null;
  risk_category: RiskCategory | null;
  verdict: string | null;
  status: SessionStatus | null;
  /** Chief Engineer (human-in-the-loop) verdict layer. Decoupled from
   *  `status` so it doesn't collide with the operational enum. Backed by
   *  the `sign_offs` audit table (migration 20260610_sign_offs.sql). */
  sign_off_status?: 'APPROVED' | 'OVERRIDDEN' | 'PENDING_REVIEW' | null;
  created_at: string;
}

export interface SignOffRow {
  sign_off_id: number;
  session_id: string;
  action: 'APPROVED' | 'OVERRIDDEN' | 'PENDING_REVIEW';
  signer_role: string;
  signer_name: string | null;
  notes: string | null;
  evidence_hash: string | null;
  signed_at: string;
}

export interface AnomalyRow {
  anomaly_id: string;
  session_id: string | null;
  rule: string;
  rule_name: string | null;
  severity: AnomalySeverity;
  triggered_at: string | null;
  source_a: string | null;
  source_b: string | null;
  dev_value: number | null;
  dev_pct: number | null;
  unit: string | null;
  description: string | null;
  acknowledged: boolean | null;
  resolved: boolean | null;
}

export interface SupplierRow {
  id: string;
  name: string;
  mpa_licence: string | null;
  licence_expiry: string | null;
  total_sessions: number | null;
  mismatch_count: number | null;
  avg_dev_pct: number | null;
  critical_count: number | null;
  lop_count: number | null;
  reputation_score: number | null;
  trend: string | null;
  flag: SupplierFlag | null;
}

export interface RiskScoreRow {
  session_id: string;
  anomaly_severity_0_100: number;
  supplier_history_0_100: number;
  doc_completeness_0_100: number;
  dev_severity_0_100: number;
  final_risk_score: number;
  risk_category: RiskCategory;
  verdict: string;
  estimated_impact_usd: number | null;
}
